### ISSUE TITLE
Can't build using MSYS2/MinGW-w64

### ISSUE THREAD

**Issue by williamjcm** [lqez/npk#11]
I tried using both "MSYS Makefiles" and "Unix Makefiles" generators.

I get the following error:

```
$ make
Scanning dependencies of target libnpkStatic
[  1%] Building C object libnpk/CMakeFiles/libnpkStatic.dir/src/npk.c.obj
In file included from C:/msys64/home/Guillaume/npk/libnpk/include/npk.h:11:0,
                 from C:/msys64/home/Guillaume/npk/libnpk/src/npk.c:12:
C:/msys64/home/Guillaume/npk/libnpk/include/npk_conf.h:41:15: error: conflicting types for 'mode_t'
   typedef int mode_t;
               ^~~~~~
In file included from C:/msys64/mingw32/i686-w64-mingw32/include/sys/stat.h:26:0,
                 from C:/msys64/home/Guillaume/npk/libnpk/src/npk.c:11:
C:/msys64/mingw32/i686-w64-mingw32/include/sys/types.h:77:17: note: previous declaration of 'mode_t' was here
 typedef _mode_t mode_t;
                 ^~~~~~
make[2]: *** [libnpk/CMakeFiles/libnpkStatic.dir/build.make:64: libnpk/CMakeFiles/libnpkStatic.dir/src/npk.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: libnpk/CMakeFiles/libnpkStatic.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

Though I use MSYS2 64-bit, I tried to build using the 32-bit version of mingw-w64 (since the 64-bit version gives a different error).

Don't hesitate to ask if you need more info.

**Comment by lqez** [comment]
Thank you for reporting. It looks like `_mode_t` is different from `int` in your platform.
Could you provide me your build environment in detail?

**Comment by williamjcm** [comment]
- Windows Server 2008 R2 x64 (also happens on Windows 10 x64)
- MSYS2 64-bit, with mingw-w64-i686

**Comment by lqez** [comment]
Got it. Thanks.

**Comment by liamedwards12** [comment]
Getting the same problems on my end (Same environment as williamjcm) (Win 10 x64), is it possible for you to include a pre compiled binary (looking a Windows one) in the repo as i can't get it going in VS either, and prefer not to mess with VS if i can help it.

Thanks.

**Comment by cometkim** [comment]
`mode_t` from `<sys/types.h>` of mingw is:
```c
#ifndef _MODE_T_
#define _MODE_T_
    typedef unsigned short _mode_t;
#ifndef NO_OLDNAMES
    typedef _mode_t mode_t;
#endif
#endif /* Not _MODE_T_ */
```

So I guess that just to add this checking would resolve the conflict.
```diff
#if defined(_WIN32) || defined(_WIN64)
    #define NPK_PLATFORM_WINDOWS
+   #if !defined _MODE_T || defined(NO_OLDNAMES)
        typedef int mode_t
+   #endif
```

**Comment by lqez** [comment]
@cometkim I missed this comment. Could you make a PR for this?
